[package]
name = "bevy_rts_pathfinding"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.2"
bevy_rapier3d = "0.27.0"
image = "0.25.5"
pathfinding = "4.11.0"

[profile.dev]
opt-level = 0
debug = true
overflow-checks = true

[profile.release]
opt-level = 3
debug = false
lto = "thin"
codegen-units = 1
